name: ci

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta

permissions:
  id-token: write
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm dev:prepare
      - run: pnpm lint
      - run: pnpm build

      - name: Publish
        if: |
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, '[skip-release]')
        run: |
          pnpm add -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/git @semantic-release/github &&
          pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
